services:
  cherrypick:
    container_name: cherrypick_db 
    env_file:
      - .env
    image: postgres:14
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./0-init-postgres.sql:/docker-entrypoint-initdb.d/0-init-postgres.sql
      - ./1-populate-postgres.sql:/docker-entrypoint-initdb.d/1-populate-postgres.sql
      - ./0-auth-schema.sql:/docker-entrypoint-initdb.d/0-auth-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

volumes:
  postgres_data:
